name: JSON check  # feel free to pick your own name
on:
  push:
    paths:
      - '**.json'
jobs:
  json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Source schema validator
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ./json/json2/test.json
          jsons: ./json/*/*.json