
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      need_to_deploy_to_stg:
        required: true
        type: boolean
        default: false
      branch_name:
        description: 'branch that you want to build from'
        required: true
        type: string
      ecr_region_name:
        description: 'like name shows'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
